name: Build and Push RAG API

on:
  push:
    branches:
      - main   # runs when you push to main branch

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write   # REQUIRED for GHCR push

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker image
        run: docker build -t ghcr.io/nicole52-web/rag-api:latest .

      - name: Push Docker image
        run: docker push ghcr.io/nicole52-web/rag-api:latest